### ISSUE TITLE
Update Mocks name generation

### ISSUE THREAD

**Issue by Arthasasyan** [axibase/atsd-api-test#542]
Current name generator create similar names for every test iteration. It can be a problem if you need to run tests several times as you need to delete what was generated every time. I suggest the following changes to `TestNameGenerator` class to guarantee unique values:

```java
String newTestName(Key key) {
        String namePrefix = getPrefix(key);
        int testNumber = prefixDictionary.computeIfAbsent(namePrefix, prefix -> new AtomicInteger((int)System.currentTimeMillis()))
                .incrementAndGet();
        return namePrefix + "-" + testNumber;
    }
```

**Comment by Arthasasyan** [comment]
Probably, `new Random().nextInt()` could be a better decision to avoid type conversions from long to int

**Comment by raipc** [comment]
Why not just add a suffix with a time of test config initialization?

**Comment by Arthasasyan** [comment]
We can add new field to TestNameGenerator class

```java
private static final String TEST_INITIALIZATION_TIME = Util.ISOFormat(System.currentTimeMillis());
```

And then rewrite function like this 

```java
String newTestName(Key key) {
        String namePrefix = getPrefix(key);
        int testNumber = prefixDictionary.computeIfAbsent(namePrefix, prefix -> new AtomicInteger(0))
                .incrementAndGet();
        return namePrefix + "-" + testNumber + "-" + TEST_INITIALIZATION_TIME;
    }
```
