### ISSUE TITLE
Lookup function call without replacement table

### ISSUE THREAD

**Issue by Arthasasyan** [axibase/atsd-api-test#556]
In some tests there is a call to lookup function to nonexistent replacement tables:

https://github.com/axibase/atsd-api-test/blob/54410b9d7ae667987dabee564ff7d3af5a5d2558/src/test/java/com/axibase/tsd/api/method/sql/function/string/CastTest.java#L530

https://github.com/axibase/atsd-api-test/blob/54410b9d7ae667987dabee564ff7d3af5a5d2558/src/test/java/com/axibase/tsd/api/method/sql/function/string/CastTest.java#L545

https://github.com/axibase/atsd-api-test/blob/54410b9d7ae667987dabee564ff7d3af5a5d2558/src/test/java/com/axibase/tsd/api/method/sql/operator/SqlLookupFunctionTest.java#L204

Now these tests are failing. All of them seem to require lookup to return NULL, but now it raises error. @raipc, how do you think, should we disable these tests or rewrite them?

**Comment by raipc** [comment]
rewrite
